name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessary for SonarCloud analysis
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # or 11/21 based on your project
          distribution: 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Build and analyze
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=<richardkesumah> -Dsonar.organization=<RichardKesumah> -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
